// Generated by CoffeeScript 1.6.3
/*global console*/

var capfirstname, chart1, checkId, checkinginfotype, congratulations, createDayToday, createGuid, createInfoDate, currentDay, data, dateString, datecreated, dayToday, daysOfWeek, daysOfWeekA, daysOfWeekB, daysOfWeekC, deadline, displayMyGoalList, displayUserList, displayprimaryGoals, emailCompletion, emailGoal, firstname, getDate, goal, goalCategory, goalChange, goalType, goalguid, goalinfo, goalmessage, goals, incentivepic, incentivetext, index, infocreated, initStudentPage, loadmyFiles, makeNewUser, makeSampleGoals, mygoaldate, myinfo, mytitle, newcreated, newgoal, newinfo, newinfocreated, newprimarygoal, notify, password, placeincentivetext, primarygoalChange, primarygoals, resetCompleted, showCongrats, updateStatus, user, userListChange, username, users;

username = '';

password = '';

deadline = '';

infocreated = [];

myinfo = [];

newcreated = '';

mygoaldate = '';

chart1 = '';

incentivepic = '';

incentivetext = '';

placeincentivetext = '';

congratulations = '';

checkinginfotype = '';

mytitle = '';

data = [];

datecreated = '';

getDate = function(d) {
  return new Date(d.createdDate);
};

dayToday = '';

currentDay = '';

dateString = '';

firstname = '';

capfirstname = '';

notify = '';

goal = '';

emailGoal = '';

updateStatus = '';

index = '';

goalguid = '';

goalinfo = [];

newinfo = '';

goalCategory = 'school';

goalType = 'solo';

daysOfWeek = [];

daysOfWeekA = [];

daysOfWeekB = [];

daysOfWeekC = [];

users = [];

goals = [];

primarygoals = [];

newinfocreated = '';

newgoal = {};

newprimarygoal = {};

user = {};

goalmessage = '';

initStudentPage = function() {
  password = prompt("What is your password?");
  if (password === "JoshB654#") {
    return $.getJSON("userlist.json", function(data) {
      localStorage.setItem("users", JSON.stringify(data));
      return displayUserList();
    });
  } else {
    return document.location.href = 'goals.php';
  }
};

resetCompleted = function() {
  goals = JSON.parse(localStorage["goals"]);
  dayToday = createDayToday();
  updateStatus = "inprogress";
  $.each(goals, function(i, goal) {
    dateString = "\"" + goal.goal.recurring + "\"";
    if ((goal.goal.status = "completed") && (dateString.search(dayToday) !== -1)) {
      return goal.goal.status = updateStatus;
    }
  });
  localStorage.setItem("goals", JSON.stringify(goals));
  goalChange();
  return displayMyGoalList();
};

checkId = function() {
  $('#checkid').show();
  return setTimeout((function() {
    return $('#theloginusername').focus();
  }), 500);
};

$("#checkid").keydown(function(event) {
  if (event.keyCode === 13) {
    return $("#loginbutton").trigger("click");
  }
});

$("#logoutbutton").click(function() {
  $('#logout').hide();
  localStorage.removeItem('firstname');
  localStorage.removeItem('goals');
  localStorage.removeItem('notify');
  localStorage.removeItem('primarygoals');
  localStorage.removeItem('secret');
  localStorage.removeItem('username');
  localStorage.removeItem('users');
  return location.reload();
});

$('#loginbutton').click(function() {
  users = JSON.parse(localStorage["users"]);
  username = $("#theloginusername").val();
  password = $("#theloginpassword").val();
  return $.each(users, function(i, user) {
    if (user.username === username && user.password === password) {
      $('#checkid').hide();
      localStorage.setItem("secret", "this is a secret");
      localStorage.setItem("username", username);
      localStorage.removeItem("users");
      return loadmyFiles();
    } else {
      return $('#errorlogin').show();
    }
  });
});

loadmyFiles = function() {
  $('#logout').show();
  username = localStorage.getItem("username");
  $.getJSON(username + "user.json", function(data) {
    var capitaliseFirstLetter;
    capitaliseFirstLetter = function(string) {
      return string.charAt(0).toUpperCase() + string.slice(1);
    };
    localStorage.setItem("user", JSON.stringify(data));
    user = JSON.parse(localStorage.getItem("user"));
    notify = user.notify;
    firstname = user.firstname;
    capfirstname = capitaliseFirstLetter(firstname);
    localStorage.setItem("firstname", capfirstname);
    localStorage.setItem("notify", notify);
    return localStorage.removeItem("user");
  });
  $.getJSON(username + "primary.json", function(data) {
    return localStorage.setItem("primarygoals", JSON.stringify(data));
  });
  return $.getJSON(username + ".json", function(data) {
    localStorage.setItem("goals", JSON.stringify(data));
    $("#goalcontent").show();
    $("#addgoal").show();
    firstname = localStorage.getItem("firstname");
    $("#studentname").html(firstname + "'s" + " Goals");
    return displayMyGoalList();
  });
};

/*
  create a guid
*/


createGuid = function() {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function(c) {
    var r, v;
    r = Math.random() * 16 | 0;
    v = (c === "x" ? r : r & 0x3 | 0x8);
    return v.toString(16);
  });
};

/*
  create a date for the goal info input
*/


createInfoDate = function() {
  var d, month, n;
  d = new Date();
  month = new Array();
  month[0] = "Jan";
  month[1] = "Feb";
  month[2] = "Mar";
  month[3] = "April";
  month[4] = "May";
  month[5] = "June";
  month[6] = "July";
  month[7] = "Aug";
  month[8] = "Sept";
  month[9] = "Oct";
  month[10] = "Nov";
  month[11] = "Dec";
  n = month[d.getMonth()];
  return newcreated = n + ' ' + d.getDate();
};

/*
  create a date for recurring goal check
*/


createDayToday = function() {
  return currentDay = new Date().getDay();
};

/*
 this function displays the list of users with a bit of fade for visual interest
*/


displayUserList = function() {
  var newHTML;
  users = JSON.parse(localStorage["users"]);
  newHTML = [];
  $.each(users, function(index, user) {
    return newHTML.push("<li data-username='" + user.username + "' data-notify='" + user.notify + "' data-firstname='" + user.firstname + "'>\n<span class='username'>" + user.username + "</span>\n<span class='userfullname'>" + user.firstname + " " + user.lastname + "</span>\n<span class='password'>" + user.password + "</span>\n<span class='notifications'>" + user.notify + "</span>\n<span><button type=\"button\" class=\"btn btn-mini btn-danger pull-right removeuser\"><b>X</b> </button></span></li>");
  });
  return $(".users").css({
    "-ms-filter": "progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",
    "-moz-opacity": 1,
    "-khtml-opacity": 1,
    opacity: 1,
    visibility: "hidden"
  }).fadeOut(0, function() {
    $(".users").html(newHTML.join(""));
    return $(".users").css({
      visibility: "visible"
    }).fadeIn(200);
  });
};

$('#adduser').click(function() {
  $("#addgoalform").hide();
  $("#addprimarygoalform").hide();
  return $("#adduserform").show();
});

/*
 this creates an array of UserGoals that is empty, adds the User to the usersArray, resaves the usersArray with the new info, then clears the form
*/


$('#saveuser').click(function() {
  datecreated = new Date().toString();
  username = $('#theusername').val();
  localStorage.setItem("username", username);
  user = {
    username: $('#theusername').val(),
    firstname: $('#thefirstname').val(),
    lastname: $('#thelastname').val(),
    password: $('#thepassword').val(),
    notify: $('#thenotifications').val()
  };
  users.push(user);
  localStorage.setItem("users", JSON.stringify(users));
  makeNewUser();
  userListChange();
  return displayUserList();
});

makeSampleGoals = function() {
  mygoaldate = createInfoDate();
  newgoal = {
    goal: {
      goalguid: createGuid(),
      category: 'school',
      datecreated: datecreated,
      goal: 'This is a Blank Goal.',
      icon: 'gift',
      status: "inprogress",
      infotype: '',
      infocreated: [],
      myinfo: [],
      recurring: '',
      completedmessage: 'Yay! You completed the Blank Goal.',
      deadline: '',
      incentivepic: '',
      incentivetext: '',
      username: username
    }
  };
  goals.push(newgoal);
  localStorage.setItem("goals", JSON.stringify(goals));
  newprimarygoal = {
    primarygoal: {
      goalguid: createGuid(),
      category: 'school',
      datecreated: datecreated,
      goal: 'This is a blank Primary Goal.',
      icon: 'gift',
      status: "inprogress",
      username: username,
      subA: {
        goalguid: createGuid(),
        goal: 'This is the First SubGoal',
        icon: 'alarm',
        status: "inprogress",
        infotype: '',
        recurring: '',
        completedmessage: 'Yay! You completed the blank First Sub Goal.',
        deadline: ''
      },
      subB: {
        goalguid: createGuid(),
        goal: 'This is the Second SubGoal',
        icon: 'umbrella',
        status: "inprogress",
        infotype: '',
        recurring: '',
        completedmessage: 'Yay! You completed the blank Second Sub Goal.',
        deadline: ''
      },
      subC: {
        goalguid: createGuid(),
        goal: 'This is the Third SubGoal',
        icon: 'silverware',
        status: "inprogress",
        infotype: '',
        recurring: '',
        completedmessage: 'Yay! You completed the blank Third Sub Goal.',
        deadline: ''
      }
    }
  };
  primarygoals.push(newprimarygoal);
  localStorage.setItem("primarygoals", JSON.stringify(primarygoals));
  $("#adduserform").hide();
  $('.textempty').val('');
  goalChange();
  return primarygoalChange();
};

/*
this uses delegate because the lines of info are dynamically placed and won't respond to a simple click. It highlights the clicked User and displays his goals
*/


$(".users").delegate("li > span.username", "click", function() {
  username = $(this).closest('li').data("username");
  localStorage.setItem("username", username);
  firstname = localStorage.getItem('firstname');
  document.location.href = 'goals.php';
  $(".goalsection").html('');
  $.getJSON(username + "primary.json", function(data) {
    return localStorage.setItem("primarygoals", JSON.stringify(data));
  });
  $.getJSON(username + ".json", function(data) {
    return localStorage.setItem("goals", JSON.stringify(data));
  });
  $(this).addClass("active").siblings("li").removeClass("active");
  if (goalType === 'solo') {
    $("#goalcontent").show();
    $('#primarygoalcontent').hide();
  } else {
    $("#goalcontent").hide();
    $('#primarygoalcontent').show();
  }
  $("#adduser").show();
  $("#addgoalform").hide();
  $("#adduserform").hide();
  $("#school").addClass('active');
  if (goalType === 'solo') {
    $("#addgoal").show();
    return displayMyGoalList();
  } else {
    $("#addprimarygoal").show();
    return displayprimaryGoals();
  }
});

$('#addgoal').click(function() {
  $("#addgoalform").show();
  $("#adduser").show();
  $("#adduserform").hide();
  return $("#addprimarygoalform").hide();
});

$('#addprimarygoal').click(function() {
  $("#addprimarygoalform").show();
  $("#addgoalform").hide();
  $("#adduser").show();
  return $("#adduserform").hide();
});

$('.sologoal').click(function() {
  $('.primarycategory').hide();
  $('.category').show();
  $('#addprimarygoal').hide();
  return $('#addgoal').show();
});

$('.primarygoal').click(function() {
  $('.primarycategory').show();
  $('.category').hide();
  $('#addprimarygoal').show();
  return $('#addgoal').hide();
});

/*
this adds a goal to the goalsArray, resaves the goalsArray with the new info, resaves the usersGoals to localstorage, then clears the form
*/


$('#savegoal').click(function() {
  datecreated = new Date().toString();
  mygoaldate = createInfoDate();
  goalguid = createGuid();
  daysOfWeek = $("input[name=days]:checked").map(function() {
    return $(this).val();
  }).get();
  newgoal = {
    goal: {
      goalguid: goalguid,
      category: $("#thecategory").val().toLowerCase(),
      datecreated: datecreated,
      goal: $("#thegoal").val(),
      icon: $("input[name=icon]:checked").val(),
      status: "inprogress",
      infotype: $("input[name=theinfotype]:checked").val(),
      infocreated: [],
      myinfo: [],
      recurring: daysOfWeek,
      completedmessage: $("#thecomplete").val(),
      deadline: $("#thedeadline").val(),
      incentivepic: $("input[name=incentivepic]:checked").val(),
      incentivetext: $("#theincentivetext").val(),
      username: username
    }
  };
  goals.push(newgoal);
  localStorage.setItem("goals", JSON.stringify(goals));
  $("#addgoalform").hide();
  $("#daysoftheweek").hide();
  $(".textempty").val('');
  $('.uncheckit input').removeAttr('checked');
  goalChange();
  return displayMyGoalList();
});

/*
this adds a goal to the goalsArray, resaves the goalsArray with the new info, resaves the usersGoals to localstorage, then clears the form
*/


$('#saveprimarygoal').click(function() {
  datecreated = new Date().toString();
  goalguid = createGuid();
  daysOfWeekA = $("#daysoftheweekA input[name=days]:checked").map(function() {
    return $(this).val();
  }).get();
  daysOfWeekB = $("#daysoftheweekB input[name=days]:checked").map(function() {
    return $(this).val();
  }).get();
  daysOfWeekC = $("#daysoftheweekC input[name=days]:checked").map(function() {
    return $(this).val();
  }).get();
  newprimarygoal = {
    primarygoal: {
      goalguid: createGuid(),
      category: $("#theprimarycategory").val().toLowerCase(),
      datecreated: datecreated,
      goal: $("#theprimarygoal").val(),
      icon: $("input[name=icon]:checked").val(),
      status: "inprogress",
      username: username,
      subA: {
        goalguid: createGuid(),
        goal: $("#thegoalA").val(),
        icon: $("#theiconsA input[name=iconA]:checked").val(),
        status: "inprogress",
        infotype: $("#infotypeA input[name=theinfotypeA]:checked").val(),
        recurring: daysOfWeekA,
        completedmessage: $("#thecompleteA").val(),
        deadline: $("#thedeadlineA").val()
      },
      subB: {
        goalguid: createGuid(),
        goal: $("#thegoalB").val(),
        icon: $("#theiconsB input[name=iconB]:checked").val(),
        status: "inprogress",
        infotype: $("#infotypeB input[name=theinfotype]:checked").val(),
        recurring: daysOfWeekB,
        completedmessage: $("#thecompleteB").val(),
        deadline: $("#thedeadlineB").val()
      },
      subC: {
        goalguid: createGuid(),
        goal: $("#thegoalC").val(),
        icon: $("#theiconsC input[name=iconC]:checked").val(),
        status: "inprogress",
        infotype: $("#infotypeC input[name=theinfotype]:checked").val(),
        recurring: daysOfWeekC,
        completedmessage: $("#thecompleteC").val(),
        deadline: $("#thedeadlineC").val()
      }
    }
  };
  primarygoals.push(newprimarygoal);
  localStorage.setItem("primarygoals", JSON.stringify(primarygoals));
  $("#addgoalform").hide();
  $("#daysoftheweek").hide();
  $(".textempty").val('');
  $('.uncheckit input').removeAttr('checked');
  primarygoalChange();
  return displayprimaryGoals();
});

$(".category").click(function() {
  goalCategory = $(this).data("category");
  return displayMyGoalList();
});

$(".primarycategory").click(function() {
  goalCategory = $(this).data("category");
  return displayprimaryGoals();
});

displayMyGoalList = function() {
  var completedHTML, inprogressHTML, missedHTML;
  completedHTML = [];
  inprogressHTML = [];
  missedHTML = [];
  goals = JSON.parse(localStorage["goals"]);
  $.each(goals, function(i, goal) {
    var compareDate, day, month, now, year;
    newinfocreated = JSON.stringify(goal.goal.infocreated);
    now = new Date();
    year = now.getFullYear();
    month = now.getMonth() + 1;
    if (month <= 9) {
      month = '0' + month;
    }
    day = now.getDate();
    if (day <= 9) {
      day = '0' + day;
    }
    compareDate = year + '-' + month + '-' + day;
    if (goal.goal.category === goalCategory) {
      if (goal.goal.deadline && (goal.goal.status === 'inprogress') && (goal.goal.deadline < compareDate)) {
        goal.goal.status = 'missed';
      }
      if (goal.goal.status === 'completed') {
        return completedHTML.push("<li class='" + goal.goal.status + "' data-info='" + goal.goal.infotype + "' data-goalguid='" + goal.goal.goalguid + "' data-incentivetext='" + goal.goal.incentivetext + "' data-incentivepic='" + goal.goal.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + goal.goal.icon + "'></i>" + goal.goal.goal + "</span>\n<span class='goaldeadline'>" + goal.goal.deadline + "</span>\n<span class='goalremove'><button type='button' class='btn btn-mini btn-danger removegoal'><b>X</b></button></span>\n<span class='goalstatus' data-goal='" + goal.goal.goal + "' ><input type='checkbox' checked/></span>\n<span><i class='fa-large icon-stats chartbutton' data-infocreated='" + newinfocreated + "' data-myinfo='[" + goal.goal.myinfo + "]' data-goal='" + goal.goal.goal + "'></i></span></li>");
      } else if (goal.goal.status === "inprogress") {
        if (goal.goal.infotype === 'text') {
          return inprogressHTML.push("<li class='" + goal.goal.status + "' data-info='" + goal.goal.infotype + "' data-goalguid='" + goal.goal.goalguid + "' data-incentivetext='" + goal.goal.incentivetext + "' data-incentivepic='" + goal.goal.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + goal.goal.icon + "'></i>" + goal.goal.goal + "</span>\n<span class='goaldeadline'>" + goal.goal.deadline + "</span>\n<span class='goalremove'><button type='button' class='btn btn-mini btn-danger removegoal' ><b>X</b></button></span>\n<span class='goalstatus' data-goal='" + goal.goal.goal + "' data-complete='" + goal.goal.completedmessage + "'><input type='checkbox' /></span>\n<span class='gatherinfo'><input type='text' name='info' class='info'/></span></li>");
        } else {
          return inprogressHTML.push("<li class='" + goal.goal.status + "' data-info='" + goal.goal.infotype + "' data-goalguid='" + goal.goal.goalguid + "' data-incentivetext='" + goal.goal.incentivetext + "' data-incentivepic='" + goal.goal.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + goal.goal.icon + "'></i>" + goal.goal.goal + "</span>\n<span class='goaldeadline'>" + goal.goal.deadline + "</span>\n<span class='goalremove'><button type='button' class='btn btn-mini btn-danger removegoal' ><b>X</b></button></span>\n<span class='goalstatus' data-goal='" + goal.goal.goal + "' data-complete='" + goal.goal.completedmessage + "'><input type='checkbox' /></span></li>");
        }
      } else {
        if (goal.goal.infotype === 'text') {
          return missedHTML.push("<li class='" + goal.goal.status + "' data-info='" + goal.goal.infotype + "' data-goalguid='" + goal.goal.goalguid + "' >\n<span class='goaltitle'><i class='fa-large icon-" + goal.goal.icon + "'></i>" + goal.goal.goal + "</span>\n<span class='goaldeadline'>" + goal.goal.deadline + "</span>\n<span class='goalremove'><button type='button' class='btn btn-mini btn-danger removegoal' ><b>X</b></button></span>\n<span class='goalstatus' data-goal='" + goal.goal.goal + "'><input type='checkbox' /></span>\n<span class='gatherinfo'><input type='text' name='info' class='info'/></span></li>");
        } else {
          return missedHTML.push("<li class='" + goal.goal.status + "' data-info='" + goal.goal.infotype + "' data-goalguid='" + goal.goal.goalguid + "' >\n<span class='goaltitle'><i class='fa-large icon-" + goal.goal.icon + "'></i>" + goal.goal.goal + "</span>\n<span class='goaldeadline'>" + goal.goal.deadline + "</span>\n<span class='goalremove'><button type='button' class='btn btn-mini btn-danger removegoal' ><b>X</b></button></span>\n<span class='goalstatus' data-goal='" + goal.goal.goal + "'><input type='checkbox' /></span></li>");
        }
      }
    }
  });
  $(".goalsinprogress").html(inprogressHTML.join(""));
  $(".goalscompleted").html(completedHTML.join(""));
  $(".goalsmissed").html(missedHTML.join(""));
  return $(".goalsection").css({
    visibility: "visible"
  }).fadeIn(200);
};

$(".goalscompleted").delegate("input[type=checkbox]", "click", function() {
  goalguid = $(this).closest('li').data("goalguid");
  emailGoal = $(this).parent().data('goal');
  $(this).closest('li').removeClass("completed").addClass("inprogress").prop("checked", false);
  updateStatus = 'inprogress';
  $.each(goals, function(index, goal) {
    if (goal.goal.goalguid === goalguid) {
      goal.goal.status = updateStatus;
      return false;
    }
  });
  localStorage.setItem("goals", JSON.stringify(goals));
  goalChange();
  return displayMyGoalList();
});

$(".goalsinprogress").delegate("input[type=checkbox]", "click", function() {
  checkinginfotype = $(this).closest('li').data('info');
  if ((!$(this).closest('li').find('input[type="text"]').val()) && (checkinginfotype === 'text')) {
    alert("You have to enter a number before this goal can be completed.");
    return $(this).removeAttr('checked');
  } else {
    goalguid = $(this).closest('li').data("goalguid");
    congratulations = $(this).parent().data("complete");
    emailGoal = $(this).parent().data('goal');
    newinfo = parseInt($(this).closest('li').find('input[type="text"]').val(), 10);
    mygoaldate = createInfoDate();
    updateStatus = 'completed';
    incentivepic = 'url("' + $(this).closest('li').data('incentivepic') + '")';
    $.each(goals, function(index, goal) {
      if (goal.goal.goalguid === goalguid) {
        if (goal.goal.infotype === 'text') {
          goal.goal.myinfo.push(newinfo);
          goal.goal.infocreated.push(mygoaldate);
        }
        goal.goal.status = updateStatus;
        goal.goal.datecompleted = mygoaldate;
        goalmessage = firstname + ' has completed this goal: ' + goal.goal.goal;
        localStorage.setItem("goalmessage", JSON.stringify(goalmessage));
        return false;
      }
    });
    localStorage.setItem("goals", JSON.stringify(goals));
    $(this).find('.info').val('');
    $(this).closest('li').removeClass("inprogress missed").addClass("completed").prop("checked", true);
    showCongrats();
    emailCompletion(goalmessage);
    goalChange();
    return displayMyGoalList();
  }
});

$(".goalsmissed").delegate("input[type=checkbox]", "click", function() {
  goalguid = $(this).closest('li').data("goalguid");
  emailGoal = $(this).parent().data('goal');
  $(this).closest('li').removeClass("missed").addClass("inprogress").prop("checked", false);
  updateStatus = 'inprogress';
  $.each(goals, function(index, goal) {
    if (goal.goal.goalguid === goalguid) {
      goal.goal.status = updateStatus;
      return false;
    }
  });
  localStorage.setItem("goals", JSON.stringify(goals));
  goalChange();
  return displayMyGoalList();
});

$(".primarygoal").click(function() {
  $('#goalcontent').hide();
  $('#primarygoalcontent').show();
  goalType = 'primary';
  return displayprimaryGoals();
});

$(".sologoal").click(function() {
  $('#goalcontent').show();
  $('#primarygoalcontent').hide();
  goalType = 'solo';
  return displayMyGoalList();
});

displayprimaryGoals = function() {
  var primaryGoalsHTML;
  primaryGoalsHTML = [];
  primarygoals = JSON.parse(localStorage["primarygoals"]);
  $.each(primarygoals, function(index, primarygoal) {
    if (primarygoal.primarygoal.category === goalCategory) {
      primaryGoalsHTML.push("<li class='parent'  data-goalguid='" + primarygoal.primarygoal.goalguid + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.icon + "'></i>" + primarygoal.primarygoal.goal + "</span>\n<span class='goalremove'><button type='button' class='btn btn-mini btn-danger removegoal' data-removegoal='" + primarygoal.primarygoal.goalguid + "'><b>X</b> </button></span></li>");
      if (primarygoal.primarygoal.subA.status === 'completed') {
        newinfocreated = JSON.stringify(primarygoal.primarygoal.subA.infocreated);
        if (primarygoal.primarygoal.subA.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subA.status + " sub' data-info='" + primarygoal.primarygoal.subA.infotype + "' data-goalguid='" + primarygoal.primarygoal.subA.goalguid + "' data-incentivetext='" + primarygoal.primarygoal.subA.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subA.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subA.icon + "'></i>" + primarygoal.primarygoal.subA.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subA.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subA.goal + "'><input type='checkbox' checked></span>\n<span><i class='fa-large icon-stats chartbutton' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subA.myinfo + "]' data-goal='" + primarygoal.primarygoal.subA.goal + "'></i></span></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subA.status + " sub'  data-info='" + primarygoal.primarygoal.subA.infotype + "' data-goalguid='" + primarygoal.primarygoal.subA.goalguid + "' data-subB='subA' data-incentivetext='" + primarygoal.primarygoal.subA.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subA.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subA.icon + "'></i>" + primarygoal.primarygoal.subA.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subA.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subA.goal + "'><input type='checkbox' checked></span>\n<span><i class='fa-large icon-stats chartbutton' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subA.myinfo + "]' data-goal='" + primarygoal.primarygoal.subA.goal + "'></i></span></li>");
        }
      } else if (primarygoal.primarygoal.subA.status === "inprogress") {
        if (primarygoal.primarygoal.subA.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subA.status + " sub'  data-info='" + primarygoal.primarygoal.subA.infotype + "' data-goalguid='" + primarygoal.primarygoal.subA.goalguid + "' data-subB='subA' data-incentivetext='" + primarygoal.primarygoal.subA.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subA.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subA.icon + "'></i>" + primarygoal.primarygoal.subA.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subA.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subA.goal + "' data-complete='" + goal.completedmessage + "'><input type='checkbox'/></span>\n<span class='gatherinfo'><input type='text' name='infoA' class='info'></span></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subA.status + " sub'  data-info='" + primarygoal.primarygoal.subA.infotype + "' data-goalguid='" + primarygoal.primarygoal.subA.goalguid + "' data-subB='subA' data-incentivetext='" + primarygoal.primarygoal.subA.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subA.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subA.icon + "'></i>" + primarygoal.primarygoal.subA.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subA.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subA.goal + "' data-complete='" + goal.completedmessage + "'><input type='checkbox'/></span></li>");
        }
      } else {
        if (primarygoal.primarygoal.subA.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subA.status + " sub'  data-info='" + primarygoal.primarygoal.subA.infotype + "' data-goalguid='" + primarygoal.primarygoal.subA.goalguid + "' data-subB='subA'>\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subA.icon + "'></i>" + primarygoal.primarygoal.subA.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subA.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subA.goal + "'><input type='checkbox'/></span></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subA.status + " sub'  data-info='" + primarygoal.primarygoal.subA.infotype + "' data-goalguid='" + primarygoal.primarygoal.subA.goalguid + "' data-subB='subA'>\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subA.icon + "'></i>" + primarygoal.primarygoal.subA.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subA.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subA.goal + "'><input type='checkbox'/></span></li>");
        }
      }
      if (primarygoal.primarygoal.subB.status === 'completed') {
        newinfocreated = JSON.stringify(primarygoal.primarygoal.subB.infocreated);
        if (primarygoal.primarygoal.subB.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subB.status + " sub'  data-info='" + primarygoal.primarygoal.subB.infotype + "' data-goalguid='" + primarygoal.primarygoal.subB.goalguid + "' data-subB='subB' data-incentivetext='" + primarygoal.primarygoal.subB.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subB.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subB.icon + "'></i>" + primarygoal.primarygoal.subB.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subB.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subB.goal + "'><input type='checkbox' checked></span>\n<span><i class='fa-large icon-stats chartbutton' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subB.myinfo + "]' data-goal='" + primarygoal.primarygoal.subB.goal + "'></i></span></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subB.status + " sub'  data-info='" + primarygoal.primarygoal.subB.infotype + "' data-goalguid='" + primarygoal.primarygoal.subB.goalguid + "' data-subB='subB' data-incentivetext='" + primarygoal.primarygoal.subB.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subB.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subB.icon + "'></i>" + primarygoal.primarygoal.subB.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subB.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subB.goal + "'><input type='checkbox' checked></span>\n<span><i class='fa-large icon-stats chartbutton' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subB.myinfo + "]' data-goal='" + primarygoal.primarygoal.subB.goal + "'></i></span></li>");
        }
      } else if (primarygoal.primarygoal.subB.status === "inprogress") {
        if (primarygoal.primarygoal.subB.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subB.status + " sub'  data-info='" + primarygoal.primarygoal.subB.infotype + "' data-goalguid='" + primarygoal.primarygoal.subB.goalguid + "' data-subB='subB' data-incentivetext='" + primarygoal.primarygoal.subB.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subB.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subB.icon + "'></i>" + primarygoal.primarygoal.subB.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subB.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subB.goal + "' data-complete='" + goal.completedmessage + "'><input type='checkbox'/></span>\n<span class='gatherinfo'><input type='text' name='info' class='info'></span></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subB.status + " sub'  data-info='" + primarygoal.primarygoal.subB.infotype + "' data-goalguid='" + primarygoal.primarygoal.subB.goalguid + "' data-subB='subB' data-incentivetext='" + primarygoal.primarygoal.subB.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subB.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subB.icon + "'></i>" + primarygoal.primarygoal.subB.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subB.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subB.goal + "' data-complete='" + goal.completedmessage + "'><input type='checkbox'/></span></li>");
        }
      } else {
        if (primarygoal.primarygoal.subB.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subB.status + " sub'  data-info='" + primarygoal.primarygoal.subB.infotype + "' data-goalguid='" + primarygoal.primarygoal.subB.goalguid + "' data-subB='subB'>\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subB.icon + "'></i>" + primarygoal.primarygoal.subB.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subB.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subB.goal + "'><input type='checkbox'/></span></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subB.status + " sub'  data-info='" + primarygoal.primarygoal.subB.infotype + "' data-goalguid='" + primarygoal.primarygoal.subB.goalguid + "' data-subB='subB'>\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subB.icon + "'></i>" + primarygoal.primarygoal.subB.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subB.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subB.goal + "'><input type='checkbox'/></span></li>");
        }
      }
      if (primarygoal.primarygoal.subC.status === 'completed') {
        newinfocreated = JSON.stringify(primarygoal.primarygoal.subC.infocreated);
        if (primarygoal.primarygoal.subC.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subC.status + " sub'  data-info='" + primarygoal.primarygoal.subC.infotype + "' data-goalguid='" + primarygoal.primarygoal.subC.goalguid + "' data-subB='subC' data-incentivetext='" + primarygoal.primarygoal.subC.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subC.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subC.icon + "'></i>" + primarygoal.primarygoal.subC.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subC.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subC.goal + "'><input type='checkbox' checked></span>\n<span><i class='fa-large icon-stats chartbutton' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subC.myinfo + "]' data-goal='" + primarygoal.primarygoal.subC.goal + "'></i></span></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subC.status + " sub'  data-info='" + primarygoal.primarygoal.subC.infotype + "' data-goalguid='" + primarygoal.primarygoal.subC.goalguid + "' data-subB='subC' data-incentivetext='" + primarygoal.primarygoal.subC.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subC.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subC.icon + "'></i>" + primarygoal.primarygoal.subC.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subC.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subC.goal + "'><input type='checkbox' checked></span>\n<span><i class='fa-large icon-stats chartbutton' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subC.myinfo + "]' data-goal='" + primarygoal.primarygoal.subC.goal + "'></i></span></li>");
        }
      } else if (primarygoal.primarygoal.subC.status === "inprogress") {
        if (primarygoal.primarygoal.subC.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subC.status + " sub'  data-info='" + primarygoal.primarygoal.subC.infotype + "' data-goalguid='" + primarygoal.primarygoal.subC.goalguid + "' data-subB='subC' data-incentivetext='" + primarygoal.primarygoal.subC.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subC.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subC.icon + "'></i>" + primarygoal.primarygoal.subC.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subC.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subC.goal + "' data-complete='" + goal.completedmessage + "'><input type='checkbox'/></span>\n<span class='gatherinfo'><input type='text' name='info' class='info'></span></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subC.status + " sub'  data-info='" + primarygoal.primarygoal.subC.infotype + "' data-goalguid='" + primarygoal.primarygoal.subC.goalguid + "' data-subB='subC' data-incentivetext='" + primarygoal.primarygoal.subC.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subC.incentivepic + "' >\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subC.icon + "'></i>" + primarygoal.primarygoal.subC.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subC.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subC.goal + "' data-complete='" + goal.completedmessage + "'><input type='checkbox'/></span></li>");
        }
      } else {
        if (primarygoal.primarygoal.subC.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subC.status + " sub'  data-info='" + primarygoal.primarygoal.subC.infotype + "' data-goalguid='" + primarygoal.primarygoal.subC.goalguid + "' data-subB='subC'>\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subC.icon + "'></i>" + primarygoal.primarygoal.subC.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subC.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subC.goal + "'><input type='checkbox'/></span></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subC.status + " sub'  data-info='" + primarygoal.primarygoal.subC.infotype + "' data-goalguid='" + primarygoal.primarygoal.subC.goalguid + "' data-subB='subC'>\n<span class='goaltitle'><i class='fa-large icon-" + primarygoal.primarygoal.subC.icon + "'></i>" + primarygoal.primarygoal.subC.goal + "</span>\n<span class='goaldeadline'>" + primarygoal.primarygoal.subC.deadline + "</span>\n<span class='goalremove primaryremove'><img src='images/spacer.png' /></span>\n<span class='goalstatus' data-goal='" + primarygoal.primarygoal.subC.goal + "'><input type='checkbox'/></span></li>");
        }
      }
    }
    return primaryGoalsHTML.push('<span class="clearfix"></span>');
  });
  return $(".primarygoals").css({
    "-ms-filter": "progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",
    "-moz-opacity": 1,
    "-khtml-opacity": 1,
    opacity: 1,
    visibility: "hidden"
  }).fadeOut(0, function() {
    $(".primarygoals").html(primaryGoalsHTML.join(""));
    return $(".primarygoals").css({
      visibility: "visible"
    }).fadeIn(200);
  });
};

$(".primarygoals").delegate("input[type=checkbox]", "click", function() {
  goalguid = $(this).closest('li').data("goalguid");
  if ($(this).closest('li').hasClass('completed')) {
    $(this).closest('li').removeClass("completed").addClass("inprogress").prop("checked", false);
    updateStatus = 'inprogress';
    $.each(primarygoals, function(index, primarygoal) {
      if (primarygoal.primarygoal.subA.goalguid === goalguid) {
        primarygoal.primarygoal.subA.status = updateStatus;
        return false;
      } else if (primarygoal.primarygoal.subB.goalguid === goalguid) {
        primarygoal.primarygoal.subB.status = updateStatus;
        return false;
      } else if (primarygoal.primarygoal.subC.goalguid === goalguid) {
        primarygoal.primarygoal.subC.status = updateStatus;
        return false;
      }
    });
    localStorage.setItem("primarygoals", JSON.stringify(primarygoals));
    primarygoalChange();
    return displayprimaryGoals();
  } else if ($(this).closest('li').hasClass('inprogress')) {
    checkinginfotype = $(this).closest('li').data('info');
    if ((!$(this).closest('li').find('input[type="text"]').val()) && (checkinginfotype === 'text')) {
      alert("You have to enter a number before this goal can be completed.");
      return $(this).removeAttr('checked');
    } else {
      newinfo = parseInt($(this).closest('li').find('input[type="text"]').val(), 10);
      mygoaldate = createInfoDate();
      updateStatus = 'completed';
      $.each(primarygoals, function(index, primarygoal) {
        if (primarygoal.primarygoal.subA.goalguid === goalguid) {
          if (primarygoal.primarygoal.subA.infotype === 'text') {
            primarygoal.primarygoal.subA.myinfo.push(newinfo);
            primarygoal.primarygoal.subA.infocreated.push(mygoaldate);
          }
          primarygoal.primarygoal.subA.status = updateStatus;
          primarygoal.primarygoal.subA.datecompleted = mygoaldate;
          goalmessage = firstname + ' has completed this goal: ' + primarygoal.primarygoal.subA.goal;
          localStorage.setItem("goalmessage", JSON.stringify(goalmessage));
          return false;
        } else if (primarygoal.primarygoal.subB.goalguid === goalguid) {
          if (primarygoal.primarygoal.subB.infotype === 'text') {
            primarygoal.primarygoal.subB.myinfo.push(newinfo);
            primarygoal.primarygoal.subB.infocreated.push(mygoaldate);
          }
          primarygoal.primarygoal.subB.status = updateStatus;
          primarygoal.primarygoal.subB.datecompleted = mygoaldate;
          goalmessage = firstname + ' has completed this goal: ' + primarygoal.primarygoal.subB.goal;
          localStorage.setItem("goalmessage", JSON.stringify(goalmessage));
          return false;
        } else if (primarygoal.primarygoal.subC.goalguid === goalguid) {
          if (primarygoal.primarygoal.subC.infotype === 'text') {
            primarygoal.primarygoal.subC.myinfo.push(newinfo);
            primarygoal.primarygoal.subC.infocreated.push(mygoaldate);
          }
          primarygoal.primarygoal.subC.status = updateStatus;
          primarygoal.primarygoal.subC.datecompleted = mygoaldate;
          goalmessage = firstname + ' has completed this goal: ' + primarygoal.primarygoal.subC.goal;
          localStorage.setItem("goalmessage", JSON.stringify(goalmessage));
          return false;
        }
      });
      localStorage.setItem("primarygoals", JSON.stringify(primarygoals));
      emailCompletion();
      $(this).find('.info').val('');
      $(this).closest('li').removeClass("inprogress missed").addClass("completed").prop("checked", true);
      emailCompletion(goalmessage);
      primarygoalChange();
      return displayprimaryGoals();
    }
  } else {
    $(this).closest('li').removeClass("missed").addClass("inprogress").prop("checked", false);
    updateStatus = 'inprogress';
    $.each(primarygoals, function(index, primarygoal) {
      if (primarygoal.primarygoal.subA.goalguid === goalguid) {
        primarygoal.primarygoal.subA.status = updateStatus;
        return false;
      } else if (primarygoal.primarygoal.subB.goalguid === goalguid) {
        primarygoal.primarygoal.subB.status = updateStatus;
        return false;
      } else if (primarygoal.primarygoal.subC.goalguid === goalguid) {
        primarygoal.primarygoal.subC.status = updateStatus;
        return false;
      }
    });
    localStorage.setItem("primarygoals", JSON.stringify(primarygoals));
    primarygoalChange();
    return displayprimaryGoals();
  }
});

/*
find and remove user function
*/


$('.users').delegate("button.removeuser", "click", function() {
  var i, shouldRemove;
  username = $(this).closest('li').data("username");
  shouldRemove = confirm("Are you sure you want to remove this student?");
  if (!shouldRemove) {
    return false;
  } else {
    i = 0;
    while (i < users.length) {
      if (users[i].username === username) {
        users.splice(i, 1);
        break;
      }
      i++;
    }
    localStorage.setItem("users", JSON.stringify(users));
    localStorage.removeItem("user");
    localStorage.removeItem("goals");
    localStorage.removeItem("primarygoals");
    userListChange();
    return displayUserList();
  }
});

/*
  delete a goal
*/


$(".goalsection").delegate("button", "click", function() {
  var i, shouldRemove;
  goalguid = $(this).closest('li').data("goalguid");
  shouldRemove = confirm("Are you sure you want to remove this goal?");
  if (!shouldRemove) {
    return false;
  } else {
    i = 0;
    while (i < goals.length) {
      if (goals[i].goal.goalguid && goals[i].goal.goalguid === goalguid) {
        goals.splice(i, 1);
        break;
      }
      i++;
    }
    localStorage.setItem("goals", JSON.stringify(goals));
    goalChange();
    return displayMyGoalList();
  }
});

/*
  delete a primarygoal
*/


$(".primarygoals").delegate("button", "click", function() {
  var i, shouldRemove;
  goalguid = $(this).closest('li').data("goalguid");
  console.log(goalguid);
  shouldRemove = confirm("Are you sure you want to remove this goal?");
  if (!shouldRemove) {
    return false;
  } else {
    i = 0;
    while (i < primarygoals.length) {
      if (primarygoals[i].primarygoal.goalguid && primarygoals[i].primarygoal.goalguid === goalguid) {
        console.log('found it');
        primarygoals.splice(i, 1);
        break;
      }
      i++;
    }
    localStorage.setItem("primarygoals", JSON.stringify(primarygoals));
    primarygoalChange();
    return displayprimaryGoals();
  }
});

$('#therecurring').click(function() {
  return $('#daysoftheweek').toggle(this.checked);
});

$('#therecurringA').click(function() {
  return $('#daysoftheweekA').toggle(this.checked);
});

$('#therecurringB').click(function() {
  return $('#daysoftheweekB').toggle(this.checked);
});

$('#therecurringC').click(function() {
  return $('#daysoftheweekC').toggle(this.checked);
});

$('#modalclose').click(function() {
  $('#adduserform').hide();
  $('#addgoalform').hide();
  return $('#addprimarygoalform').hide();
});

/*
  let's build a chart
*/


$(".goalscompleted").on("click", "i.chartbutton", function() {
  $("#chartbox").show();
  $("#incentivebox").css('top', -10);
  $("#incentivebox").css('right', 25);
  $("#incentivebox").show();
  $(".chart-backdrop").show();
  incentivetext = $(this).closest('li').data('incentivetext');
  incentivepic = 'url("' + $(this).closest('li').data('incentivepic') + '")';
  placeincentivetext = '<p>' + incentivetext + '</p>';
  $("#incentivetext").html(placeincentivetext);
  $("#incentivepic").css('background-image', incentivepic);
  infocreated = $(this).data('infocreated');
  myinfo = $(this).data('myinfo');
  mytitle = $(this).data('goal');
  $(function() {});
  return $("#thischart").highcharts({
    chart: {},
    title: {
      text: mytitle
    },
    legend: {
      enabled: false
    },
    xAxis: {
      categories: infocreated
    },
    series: [
      {
        data: myinfo
      }
    ]
  });
});

$(".primarygoals").on("click", "i.chartbutton", function() {
  $("#chartbox").show();
  $("#incentivebox").css('top', -10);
  $("#incentivebox").css('right', 25);
  $("#incentivebox").show();
  $(".chart-backdrop").show();
  incentivetext = $(this).closest('li').data('incentivetext');
  incentivepic = 'url("' + $(this).closest('li').data('incentivepic') + '")';
  placeincentivetext = '<p>' + incentivetext + '</p>';
  $("#incentivetext").html(placeincentivetext);
  $("#incentivepic").css('background-image', incentivepic);
  infocreated = $(this).data('infocreated');
  myinfo = $(this).data('myinfo');
  mytitle = $(this).data('goal');
  $(function() {});
  return $("#thischart").highcharts({
    chart: {},
    title: {
      text: mytitle
    },
    legend: {
      enabled: false
    },
    xAxis: {
      categories: infocreated
    },
    series: [
      {
        data: myinfo
      }
    ]
  });
});

$('.hidechart').click(function() {
  $("#chartbox").hide();
  $("#incentivebox").hide();
  return $(".chart-backdrop").hide();
});

showCongrats = function() {
  $("#incentivebox").css('top', -90);
  $("#incentivebox").css('right', 430);
  placeincentivetext = '<p>' + congratulations + '</p>';
  $("#incentivetext").html(placeincentivetext);
  $("#incentivepic").css('background-image', incentivepic);
  $("#incentivebox").fadeIn("slow");
  return setTimeout("$('#incentivebox').hide();", 5000);
};

emailCompletion = function() {
  var postThis;
  postThis = {};
  postThis.notify = localStorage.getItem("notify");
  postThis.goalmessage = localStorage.getItem("goalmessage");
  console.log(goalmessage);
  return $.ajax({
    url: "goalNotify.php",
    type: "POST",
    data: postThis,
    success: function(response, textStatus, jqXHR) {
      return console.log("Yay, the email notify worked!");
    },
    error: function(jqXHR, textStatus, errorThrown) {
      return console.log("Didn't work so good...");
    }
  });
};

makeNewUser = function() {
  var postThis;
  postThis = {};
  postThis.username = localStorage.getItem("username");
  username = localStorage.getItem('username');
  postThis.userid = username;
  return $.ajax({
    url: "newUser.php",
    type: "POST",
    data: postThis,
    success: function(response, textStatus, jqXHR) {
      console.log("Yay, make new user worked!");
      return makeSampleGoals();
    },
    error: function(jqXHR, textStatus, errorThrown) {
      return console.log("Make new user didn't work so good...");
    }
  });
};

userListChange = function() {
  var postThis;
  postThis = {};
  postThis.users = localStorage.getItem("users");
  console.log(users);
  return $.ajax({
    url: "userList.php",
    type: "POST",
    data: postThis,
    success: function(response, textStatus, jqXHR) {
      return console.log("Yay, the userList save worked!");
    },
    error: function(jqXHR, textStatus, errorThrown) {
      return console.log("UserList save didn't work so good...");
    }
  });
};

goalChange = function() {
  var postThis;
  postThis = {};
  postThis.goals = localStorage.getItem("goals");
  username = localStorage.getItem('username');
  postThis.userid = username;
  return $.ajax({
    url: "goalChange.php",
    type: "POST",
    data: postThis,
    success: function(response, textStatus, jqXHR) {
      return console.log("Yay, the goalChange save worked!");
    },
    error: function(jqXHR, textStatus, errorThrown) {
      return console.log("GoalChange save didn't work so good...");
    }
  });
};

primarygoalChange = function() {
  var postThis;
  postThis = {};
  postThis.primarygoals = localStorage.getItem("primarygoals");
  username = localStorage.getItem('username');
  postThis.userid = username;
  return $.ajax({
    url: "primarygoalChange.php",
    type: "POST",
    data: postThis,
    success: function(response, textStatus, jqXHR) {
      return console.log("Yay, the primaryGoal save worked!");
    },
    error: function(jqXHR, textStatus, errorThrown) {
      return console.log("PrimaryGoal save didn't work so good...");
    }
  });
};
