// Generated by CoffeeScript 1.6.3
/*global console*/

var capfirstname, chart1, checkId, checkinginfotype, congratulations, createDayToday, createInfoDate, currentDay, data, dateString, datecreated, dayToday, daysOfWeek, daysOfWeekA, daysOfWeekB, daysOfWeekC, deadline, displayMyGoalList, displayprimaryGoals, emailCompletion, emailGoal, firstname, getDate, goal, goalCategory, goalChange, goalType, goalguid, goalinfo, goalmessage, goals, incentivepic, incentivetext, index, infocreated, loadmyFiles, mygoaldate, myinfo, mytitle, newcreated, newgoal, newinfo, newinfocreated, newprimarygoal, notify, password, placeincentivetext, primarygoalChange, primarygoals, resetCompleted, showCongrats, updateStatus, user, username, users;

username = '';

password = '';

deadline = '';

infocreated = [];

myinfo = [];

newcreated = '';

mygoaldate = '';

chart1 = '';

incentivepic = '';

incentivetext = '';

placeincentivetext = '';

congratulations = '';

checkinginfotype = '';

mytitle = '';

data = [];

datecreated = '';

getDate = function(d) {
  return new Date(d.createdDate);
};

dayToday = '';

currentDay = '';

dateString = '';

firstname = '';

capfirstname = '';

notify = '';

goal = '';

emailGoal = '';

updateStatus = '';

index = '';

goalguid = '';

goalinfo = [];

newinfo = '';

goalCategory = 'school';

goalType = 'solo';

daysOfWeek = [];

daysOfWeekA = [];

daysOfWeekB = [];

daysOfWeekC = [];

users = [];

goals = [];

primarygoals = [];

newinfocreated = '';

newgoal = {};

newprimarygoal = {};

user = {};

goalmessage = '';

resetCompleted = function() {
  console.log('reset triggered');
  goals = JSON.parse(localStorage["goals"]);
  dayToday = createDayToday();
  updateStatus = "inprogress";
  $.each(goals, function(i, goal) {
    dateString = "\"" + goal.goal.recurring + "\"";
    if ((goal.goal.status = "completed") && (dateString.search(dayToday) !== -1)) {
      return goal.goal.status = updateStatus;
    }
  });
  localStorage.setItem("goals", JSON.stringify(goals));
  goalChange();
  return displayMyGoalList();
};

checkId = function() {
  if (localStorage.getItem('username') !== null) {
    return loadmyFiles();
  } else {
    $('#checkid').show();
    return setTimeout((function() {
      return $('#theloginusername').focus();
    }), 500);
  }
};

/*
  create a date for the goal info input
*/


createInfoDate = function() {
  var d, month, n;
  d = new Date();
  month = new Array();
  month[0] = "Jan";
  month[1] = "Feb";
  month[2] = "Mar";
  month[3] = "April";
  month[4] = "May";
  month[5] = "June";
  month[6] = "July";
  month[7] = "Aug";
  month[8] = "Sept";
  month[9] = "Oct";
  month[10] = "Nov";
  month[11] = "Dec";
  n = month[d.getMonth()];
  return newcreated = n + ' ' + d.getDate();
};

/*
  create a date for recurring goal check
*/


createDayToday = function() {
  return currentDay = new Date().getDay();
};

$("#checkid").keydown(function(event) {
  if (event.keyCode === 13) {
    return $("#loginbutton").trigger("click");
  }
});

$("#logoutbutton").click(function() {
  $('#logout').hide();
  console.log('logged out');
  localStorage.removeItem('firstname');
  localStorage.removeItem('goals');
  localStorage.removeItem('notify');
  localStorage.removeItem('primarygoals');
  localStorage.removeItem('secret');
  localStorage.removeItem('username');
  localStorage.removeItem('users');
  return location.reload();
});

$('#loginbutton').click(function() {
  console.log('logged in');
  users = JSON.parse(localStorage["users"]);
  username = $("#theloginusername").val();
  password = $("#theloginpassword").val();
  console.log(username + '  ' + password);
  return $.each(users, function(i, user) {
    if (user.username === username && user.password === password) {
      $('#checkid').hide();
      localStorage.setItem("secret", "this is a secret");
      localStorage.setItem("username", username);
      localStorage.removeItem("users");
      return loadmyFiles();
    } else {
      return $('#errorlogin').show();
    }
  });
});

loadmyFiles = function() {
  username = localStorage.getItem("username");
  $('#checkid').hide();
  $('#logout').hide();
  $('#home').removeClass('currentmenu');
  $('#school').addClass('currentmenu');
  $('#work').removeClass('currentmenu');
  $('#personal').removeClass('currentmenu');
  $('#goalscontainer').show();
  $.getJSON(username + "user.json", function(data) {
    var capitaliseFirstLetter;
    capitaliseFirstLetter = function(string) {
      return string.charAt(0).toUpperCase() + string.slice(1);
    };
    localStorage.setItem("user", JSON.stringify(data));
    user = JSON.parse(localStorage.getItem("user"));
    notify = user.notify;
    firstname = user.firstname;
    capfirstname = capitaliseFirstLetter(firstname);
    localStorage.setItem("firstname", capfirstname);
    localStorage.setItem("notify", notify);
    localStorage.removeItem("user");
    return localStorage.removeItem("users");
  });
  $.getJSON(username + "primary.json", function(data) {
    return localStorage.setItem("primarygoals", JSON.stringify(data));
  });
  return $.getJSON(username + ".json", function(data) {
    localStorage.setItem("goals", JSON.stringify(data));
    $("#goalcontent").show();
    $("#addgoal").show();
    firstname = localStorage.getItem("firstname");
    $("#studentname").html(firstname + "'s" + " Goals");
    $('#goalscontainer').show();
    $('#primarygoalscontainer').show();
    $('#logout').hide();
    $('#checkid').hide();
    displayMyGoalList();
    return displayprimaryGoals();
  });
};

$('#home').click(function() {
  $('#home').addClass('currentmenu');
  $('#school').removeClass('currentmenu');
  $('#work').removeClass('currentmenu');
  $('#personal').removeClass('currentmenu');
  $('#goalscontainer').hide();
  if (localStorage.getItem('username') !== null) {
    return $('#logout').show();
  } else {
    return $('#checkid').show();
  }
});

$('#school').click(function() {
  $('#home').removeClass('currentmenu');
  $('#school').addClass('currentmenu');
  $('#work').removeClass('currentmenu');
  $('#personal').removeClass('currentmenu');
  $('#checkid').hide();
  $('#logout').hide();
  $('#goalscontainer').show();
  goalCategory = "school";
  displayMyGoalList();
  return displayprimaryGoals();
});

$('#work').click(function() {
  $('#home').removeClass('currentmenu');
  $('#school').removeClass('currentmenu');
  $('#work').addClass('currentmenu');
  $('#personal').removeClass('currentmenu');
  $('#checkid').hide();
  $('#logout').hide();
  $('#goalscontainer').show();
  goalCategory = "work";
  displayMyGoalList();
  return displayprimaryGoals();
});

$('#personal').click(function() {
  $('#home').removeClass('currentmenu');
  $('#school').removeClass('currentmenu');
  $('#work').removeClass('currentmenu');
  $('#personal').addClass('currentmenu');
  $('#checkid').hide();
  $('#logout').hide();
  $('#goalscontainer').show();
  goalCategory = "personal";
  displayMyGoalList();
  return displayprimaryGoals();
});

displayMyGoalList = function() {
  var completedHTML, inprogressHTML;
  completedHTML = [];
  inprogressHTML = [];
  goals = JSON.parse(localStorage["goals"]);
  $.each(goals, function(i, goal) {
    var compareDate, day, month, now, year;
    newinfocreated = JSON.stringify(goal.goal.infocreated);
    now = new Date();
    year = now.getFullYear();
    month = now.getMonth() + 1;
    if (month <= 9) {
      month = '0' + month;
    }
    day = now.getDate();
    if (day <= 9) {
      day = '0' + day;
    }
    compareDate = year + '-' + month + '-' + day;
    if (goal.goal.category === goalCategory) {
      if (goal.goal.deadline && (goal.goal.status === 'inprogress') && (goal.goal.deadline < compareDate)) {
        goal.goal.status = 'missed';
      }
      if (goal.goal.status === 'completed') {
        return completedHTML.push("<li class='" + goal.goal.status + "' data-info='" + goal.goal.infotype + "' data-goalguid='" + goal.goal.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + goal.goal.myinfo + "]' data-incentivetext='" + goal.goal.incentivetext + "' data-incentivepic='" + goal.goal.incentivepic + "' data-goal='" + goal.goal.goal + "' data-complete='" + goal.goal.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + goal.goal.icon + "'></i></span>\n  <span class='goaltitle'>" + goal.goal.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' checked /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n</div></li>");
      } else if (goal.goal.status === "inprogress") {
        if (goal.goal.infotype === 'text') {
          return inprogressHTML.push("<li class='" + goal.goal.status + "' data-info='" + goal.goal.infotype + "' data-goalguid='" + goal.goal.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + goal.goal.myinfo + "]' data-incentivetext='" + goal.goal.incentivetext + "' data-incentivepic='" + goal.goal.incentivepic + "' data-goal='" + goal.goal.goal + "' data-complete='" + goal.goal.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + goal.goal.icon + "'></i></span>\n  <span class='goaltitle'>" + goal.goal.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n     <label class='gatherinfo'>\n       <input type='number' name='info' class='info' />&nbsp; Enter a number.\n     </label>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n  <span class='goaldeadline'>Deadline: " + goal.goal.deadline + "</span>\n</div></li>");
        } else {
          return inprogressHTML.push("<li class='" + goal.goal.status + "' data-info='" + goal.goal.infotype + "' data-goalguid='" + goal.goal.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + goal.goal.myinfo + "]' data-incentivetext='" + goal.goal.incentivetext + "' data-incentivepic='" + goal.goal.incentivepic + "' data-goal='" + goal.goal.goal + "' data-complete='" + goal.goal.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + goal.goal.icon + "'></i></span>\n  <span class='goaltitle'>" + goal.goal.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n  <span class='goaldeadline'>Deadline: " + goal.goal.deadline + "</span>\n</div></li>");
        }
      }
    }
  });
  $(".goalsinprogress").html(inprogressHTML.join(""));
  return $(".goalscompleted").html(completedHTML.join(""));
};

$(".goalscompleted").delegate("input[type=checkbox]", "click", function() {
  goalguid = $(this).closest('li').data("goalguid");
  emailGoal = $(this).closest('li').data('goal');
  $(this).closest('li').removeClass("completed").addClass("inprogress").prop("checked", false);
  updateStatus = 'inprogress';
  $.each(goals, function(index, goal) {
    if (goal.goal.goalguid === goalguid) {
      goal.goal.status = updateStatus;
      return false;
    }
  });
  localStorage.setItem("goals", JSON.stringify(goals));
  goalChange();
  return displayMyGoalList();
});

$(".goalsinprogress").delegate("input[name=completedyes]", "click", function() {
  checkinginfotype = $(this).closest('li').data('info');
  if ((!$(this).closest('li').find('input[name="info"]').val()) && (checkinginfotype === 'text')) {
    alert("You have to enter a number before this goal can be completed.");
    return $(this).removeAttr('checked');
  } else {
    goalguid = $(this).closest('li').data("goalguid");
    congratulations = $(this).closest('li').data("complete");
    emailGoal = $(this).closest('li').data('goal');
    newinfo = parseInt($(this).closest('li').find('input[type="number"]').val(), 10);
    mygoaldate = createInfoDate();
    updateStatus = 'completed';
    incentivepic = 'url("' + $(this).closest('li').data('incentivepic') + '")';
    $.each(goals, function(index, goal) {
      if (goal.goal.goalguid === goalguid) {
        if (goal.goal.infotype === 'text') {
          goal.goal.myinfo.push(newinfo);
          goal.goal.infocreated.push(mygoaldate);
        }
        goal.goal.status = updateStatus;
        goal.goal.datecompleted = mygoaldate;
        goalmessage = firstname + ' has completed this goal: ' + goal.goal.goal;
        localStorage.setItem("goalmessage", JSON.stringify(goalmessage));
        return false;
      }
    });
    localStorage.setItem("goals", JSON.stringify(goals));
    $(this).find('.info').val('');
    $(this).closest('li').removeClass("inprogress missed").addClass("completed").prop("checked", true);
    showCongrats();
    emailCompletion(goalmessage);
    goalChange();
    return displayMyGoalList();
  }
});

displayprimaryGoals = function() {
  var primaryGoalsHTML;
  primaryGoalsHTML = [];
  primarygoals = JSON.parse(localStorage["primarygoals"]);
  $.each(primarygoals, function(index, primarygoal) {
    if (primarygoal.primarygoal.category === goalCategory) {
      primaryGoalsHTML.push("<li class='parent'  data-goalguid='" + primarygoal.primarygoal.goalguid + "' >\n<div class='goalupper'>\n   <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.icon + "'></i></span>\n   <span class='goaltitle'>" + primarygoal.primarygoal.goal + "</span>\n</div></li>");
      if (primarygoal.primarygoal.subA.status === 'completed') {
        newinfocreated = JSON.stringify(primarygoal.primarygoal.subA.infocreated);
        primarygoal.primarygoal.subA.infotype === 'text';
        primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subA.status + " sub' data-info='" + primarygoal.primarygoal.subA.infotype + "' data-goalguid='" + primarygoal.primarygoal.subA.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subA.myinfo + "]' data-incentivetext='" + primarygoal.primarygoal.subA.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subA.incentivepic + "' data-goal='" + primarygoal.primarygoal.subA.goal + "' data-complete='" + primarygoal.primarygoal.subA.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.subA.icon + "'></i></span>\n  <span class='goaltitle'>" + primarygoal.primarygoal.subA.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' checked /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n</div></li>");
      } else if (primarygoal.primarygoal.subA.status === "inprogress") {
        if (primarygoal.primarygoal.subA.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subA.status + " sub' data-info='" + primarygoal.primarygoal.subA.infotype + "' data-goalguid='" + primarygoal.primarygoal.subA.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subA.myinfo + "]' data-incentivetext='" + primarygoal.primarygoal.subA.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subA.incentivepic + "' data-goal='" + primarygoal.primarygoal.subA.goal + "' data-complete='" + primarygoal.primarygoal.subA.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.subA.icon + "'></i></span>\n  <span class='goaltitle'>" + primarygoal.primarygoal.subA.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n     <label class='gatherinfo'>\n       <input type='number' name='info' class='info' />&nbsp; Enter a number.\n     </label>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n  <span class='goaldeadline'>Deadline: " + primarygoal.primarygoal.subA.deadline + "</span>\n</div></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subA.status + " sub' data-info='" + primarygoal.primarygoal.subA.infotype + "' data-goalguid='" + primarygoal.primarygoal.subA.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subA.myinfo + "]' data-incentivetext='" + primarygoal.primarygoal.subA.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subA.incentivepic + "' data-goal='" + primarygoal.primarygoal.subA.goal + "' data-complete='" + primarygoal.primarygoal.subA.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.subA.icon + "'></i></span>\n  <span class='goaltitle'>" + primarygoal.primarygoal.subA.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n  <span class='goaldeadline'>Deadline: " + primarygoal.primarygoal.subA.deadline + "</span>\n</div></li>");
        }
      }
      if (primarygoal.primarygoal.subB.status === 'completed') {
        newinfocreated = JSON.stringify(primarygoal.primarygoal.subB.infocreated);
        primarygoal.primarygoal.subB.infotype === 'text';
        primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subB.status + " sub' data-info='" + primarygoal.primarygoal.subB.infotype + "' data-goalguid='" + primarygoal.primarygoal.subB.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subB.myinfo + "]' data-incentivetext='" + primarygoal.primarygoal.subB.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subB.incentivepic + "' data-goal='" + primarygoal.primarygoal.subB.goal + "' data-complete='" + primarygoal.primarygoal.subB.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.subB.icon + "'></i></span>\n  <span class='goaltitle'>" + primarygoal.primarygoal.subB.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' checked /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n</div></li>");
      } else if (primarygoal.primarygoal.subB.status === "inprogress") {
        if (primarygoal.primarygoal.subB.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subB.status + " sub' data-info='" + primarygoal.primarygoal.subB.infotype + "' data-goalguid='" + primarygoal.primarygoal.subB.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subB.myinfo + "]' data-incentivetext='" + primarygoal.primarygoal.subB.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subB.incentivepic + "' data-goal='" + primarygoal.primarygoal.subB.goal + "' data-complete='" + primarygoal.primarygoal.subB.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.subB.icon + "'></i></span>\n  <span class='goaltitle'>" + primarygoal.primarygoal.subB.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n     <label class='gatherinfo'>\n       <input type='number' name='info' class='info' />&nbsp; Enter a number.\n     </label>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n  <span class='goaldeadline'>Deadline: " + primarygoal.primarygoal.subB.deadline + "</span>\n</div></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subB.status + " sub' data-info='" + primarygoal.primarygoal.subB.infotype + "' data-goalguid='" + primarygoal.primarygoal.subB.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subB.myinfo + "]' data-incentivetext='" + primarygoal.primarygoal.subB.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subB.incentivepic + "' data-goal='" + primarygoal.primarygoal.subB.goal + "' data-complete='" + primarygoal.primarygoal.subB.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.subB.icon + "'></i></span>\n  <span class='goaltitle'>" + primarygoal.primarygoal.subB.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n  <span class='goaldeadline'>Deadline: " + primarygoal.primarygoal.subB.deadline + "</span>\n</div></li>");
        }
      }
      if (primarygoal.primarygoal.subC.status === 'completed') {
        newinfocreated = JSON.stringify(primarygoal.primarygoal.subC.infocreated);
        primarygoal.primarygoal.subC.infotype === 'text';
        primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subC.status + " sub' data-info='" + primarygoal.primarygoal.subC.infotype + "' data-goalguid='" + primarygoal.primarygoal.subC.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subC.myinfo + "]' data-incentivetext='" + primarygoal.primarygoal.subC.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subC.incentivepic + "' data-goal='" + primarygoal.primarygoal.subC.goal + "' data-complete='" + primarygoal.primarygoal.subC.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.subC.icon + "'></i></span>\n  <span class='goaltitle'>" + primarygoal.primarygoal.subC.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' checked /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n</div></li>");
      } else if (primarygoal.primarygoal.subC.status === "inprogress") {
        if (primarygoal.primarygoal.subC.infotype === 'text') {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subC.status + " sub' data-info='" + primarygoal.primarygoal.subC.infotype + "' data-goalguid='" + primarygoal.primarygoal.subC.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subC.myinfo + "]' data-incentivetext='" + primarygoal.primarygoal.subC.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subC.incentivepic + "' data-goal='" + primarygoal.primarygoal.subC.goal + "' data-complete='" + primarygoal.primarygoal.subC.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.subC.icon + "'></i></span>\n  <span class='goaltitle'>" + primarygoal.primarygoal.subC.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n     <label class='gatherinfo'>\n       <input type='number' name='info' class='info' />&nbsp; Enter a number.\n     </label>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n  <span class='goaldeadline'>Deadline: " + primarygoal.primarygoal.subC.deadline + "</span>\n</div></li>");
        } else {
          primaryGoalsHTML.push("<li class='" + primarygoal.primarygoal.subC.status + " sub' data-info='" + primarygoal.primarygoal.subC.infotype + "' data-goalguid='" + primarygoal.primarygoal.subC.goalguid + "' data-infocreated='" + newinfocreated + "' data-myinfo='[" + primarygoal.primarygoal.subC.myinfo + "]' data-incentivetext='" + primarygoal.primarygoal.subC.incentivetext + "' data-incentivepic='" + primarygoal.primarygoal.subC.incentivepic + "' data-goal='" + primarygoal.primarygoal.subC.goal + "' data-complete='" + primarygoal.primarygoal.subC.completedmessage + "'>\n<div class='goalupper'>\n  <span class='goalicon'><i class='fa-medium details icon-" + primarygoal.primarygoal.subC.icon + "'></i></span>\n  <span class='goaltitle'>" + primarygoal.primarygoal.subC.goal + "</span>\n  <span class='thechartbutton'><i class='fa-medium icon-stats chartbutton' ></i></span>\n</div>\n<div class='goallower'>\n  <div class='control-group uncheckit' >\n    <label class='control-label thequestion' for='completedquestion'>Did you complete this goal?</label>\n    <div class='controls theanswer'>\n      <label class='radio'>\n       <input type='radio' name='completedyes' value='true' /> Yes\n      </label>\n      <label class='radio'>\n       <input type='radio' name='completedno' value='false' /> No\n      </label>\n    </div>\n  </div>\n  <span class='goaldeadline'>Deadline: " + primarygoal.primarygoal.subC.deadline + "</span>\n</div></li>");
        }
      }
    }
    return primaryGoalsHTML.push('<span class="clearfix"></span>');
  });
  return $(".primarygoals").html(primaryGoalsHTML.join(""));
};

$(".primarygoals").delegate("input[name='completedyes']", "click", function() {
  goalguid = $(this).closest('li').data("goalguid");
  if ($(this).closest('li').hasClass('completed')) {
    $(this).closest('li').removeClass("completed").addClass("inprogress").prop("checked", false);
    updateStatus = 'inprogress';
    $.each(primarygoals, function(index, primarygoal) {
      if (primarygoal.primarygoal.subA.goalguid === goalguid) {
        primarygoal.primarygoal.subA.status = updateStatus;
        return false;
      } else if (primarygoal.primarygoal.subB.goalguid === goalguid) {
        primarygoal.primarygoal.subB.status = updateStatus;
        return false;
      } else if (primarygoal.primarygoal.subC.goalguid === goalguid) {
        primarygoal.primarygoal.subC.status = updateStatus;
        return false;
      }
    });
    localStorage.setItem("primarygoals", JSON.stringify(primarygoals));
    primarygoalChange();
    return displayprimaryGoals();
  } else if ($(this).closest('li').hasClass('inprogress')) {
    checkinginfotype = $(this).closest('li').data('info');
    if ((!$(this).closest('li').find('input[type="number"]').val()) && (checkinginfotype === 'text')) {
      alert("You have to enter a number before this goal can be completed.");
      return $(this).removeAttr('checked');
    } else {
      newinfo = parseInt($(this).closest('li').find('input[type="number"]').val(), 10);
      mygoaldate = createInfoDate();
      updateStatus = 'completed';
      $.each(primarygoals, function(index, primarygoal) {
        if (primarygoal.primarygoal.subA.goalguid === goalguid) {
          if (primarygoal.primarygoal.subA.infotype === 'text') {
            primarygoal.primarygoal.subA.myinfo.push(newinfo);
            primarygoal.primarygoal.subA.infocreated.push(mygoaldate);
          }
          primarygoal.primarygoal.subA.status = updateStatus;
          primarygoal.primarygoal.subA.datecompleted = mygoaldate;
          goalmessage = firstname + ' has completed this goal: ' + primarygoal.primarygoal.subA.goal;
          localStorage.setItem("goalmessage", JSON.stringify(goalmessage));
          return false;
        } else if (primarygoal.primarygoal.subB.goalguid === goalguid) {
          if (primarygoal.primarygoal.subB.infotype === 'text') {
            primarygoal.primarygoal.subB.myinfo.push(newinfo);
            primarygoal.primarygoal.subB.infocreated.push(mygoaldate);
          }
          primarygoal.primarygoal.subB.status = updateStatus;
          primarygoal.primarygoal.subB.datecompleted = mygoaldate;
          goalmessage = firstname + ' has completed this goal: ' + primarygoal.primarygoal.subB.goal;
          localStorage.setItem("goalmessage", JSON.stringify(goalmessage));
          return false;
        } else if (primarygoal.primarygoal.subC.goalguid === goalguid) {
          if (primarygoal.primarygoal.subC.infotype === 'text') {
            primarygoal.primarygoal.subC.myinfo.push(newinfo);
            primarygoal.primarygoal.subC.infocreated.push(mygoaldate);
          }
          primarygoal.primarygoal.subC.status = updateStatus;
          primarygoal.primarygoal.subC.datecompleted = mygoaldate;
          goalmessage = firstname + ' has completed this goal: ' + primarygoal.primarygoal.subC.goal;
          localStorage.setItem("goalmessage", JSON.stringify(goalmessage));
          return false;
        }
      });
      localStorage.setItem("primarygoals", JSON.stringify(primarygoals));
      emailCompletion();
      $(this).find('.info').val('');
      $(this).closest('li').removeClass("inprogress missed").addClass("completed").prop("checked", true);
      emailCompletion(goalmessage);
      primarygoalChange();
      return displayprimaryGoals();
    }
  } else {
    $(this).closest('li').removeClass("missed").addClass("inprogress").prop("checked", false);
    updateStatus = 'inprogress';
    $.each(primarygoals, function(index, primarygoal) {
      if (primarygoal.primarygoal.subA.goalguid === goalguid) {
        primarygoal.primarygoal.subA.status = updateStatus;
        return false;
      } else if (primarygoal.primarygoal.subB.goalguid === goalguid) {
        primarygoal.primarygoal.subB.status = updateStatus;
        return false;
      } else if (primarygoal.primarygoal.subC.goalguid === goalguid) {
        primarygoal.primarygoal.subC.status = updateStatus;
        return false;
      }
    });
    localStorage.setItem("primarygoals", JSON.stringify(primarygoals));
    primarygoalChange();
    return displayprimaryGoals();
  }
});

$('#therecurring').click(function() {
  return $('#daysoftheweek').toggle(this.checked);
});

$('#therecurringA').click(function() {
  return $('#daysoftheweekA').toggle(this.checked);
});

$('#therecurringB').click(function() {
  return $('#daysoftheweekB').toggle(this.checked);
});

$('#therecurringC').click(function() {
  return $('#daysoftheweekC').toggle(this.checked);
});

$('#modalclose').click(function() {
  $('#adduserform').hide();
  $('#addgoalform').hide();
  return $('#addprimarygoalform').hide();
});

/*
  open and close the details div of a goal
*/


$(".goalsection").on("click", "span.goaltitle", function() {
  if ($(this).parent().siblings('.goallower').hasClass('showdetails')) {
    $(this).parent().siblings('.goallower').removeClass('showdetails');
  } else {
    $(".goallower").removeClass('showdetails');
    $(this).parent().siblings('.goallower').addClass('showdetails');
  }
  return false;
});

$(".primarygoals").on("click", "span.goaltitle", function() {
  if ($(this).parent().siblings('.goallower').hasClass('showdetails')) {
    $(this).parent().siblings('.goallower').removeClass('showdetails');
  } else {
    $(".goallower").removeClass('showdetails');
    $(this).parent().siblings('.goallower').addClass('showdetails');
  }
  return false;
});

/*
  let's build a chart
*/


$(".goalsection").on("click", "i.chartbutton", function() {
  $("#chartbox").show();
  $("#incentivebox").css('top', -10);
  $("#incentivebox").css('right', 25);
  $("#incentivebox").show();
  $(".chart-backdrop").show();
  incentivetext = $(this).closest('li').data('incentivetext');
  incentivepic = 'url("' + $(this).closest('li').data('incentivepic') + '")';
  placeincentivetext = '<p>' + incentivetext + '</p>';
  $("#incentivetext").html(placeincentivetext);
  $("#incentivepic").css('background-image', incentivepic);
  infocreated = $(this).closest('li').data('infocreated');
  myinfo = $(this).closest('li').data('myinfo');
  mytitle = $(this).closest('li').data('goal');
  $(function() {});
  return $("#thischart").highcharts({
    chart: {},
    title: {
      text: mytitle
    },
    legend: {
      enabled: false
    },
    xAxis: {
      categories: infocreated
    },
    series: [
      {
        data: myinfo
      }
    ]
  });
});

$(".primarygoals").on("click", "i.chartbutton", function() {
  $("#chartbox").show();
  $("#incentivebox").css('top', -10);
  $("#incentivebox").css('right', 25);
  $("#incentivebox").show();
  $(".chart-backdrop").show();
  incentivetext = $(this).closest('li').data('incentivetext');
  incentivepic = 'url("' + $(this).closest('li').data('incentivepic') + '")';
  placeincentivetext = '<p>' + incentivetext + '</p>';
  $("#incentivetext").html(placeincentivetext);
  $("#incentivepic").css('background-image', incentivepic);
  infocreated = $(this).closest('li').data('infocreated');
  myinfo = $(this).closest('li').data('myinfo');
  mytitle = $(this).closest('li').data('goal');
  $(function() {});
  return $("#thischart").highcharts({
    chart: {},
    title: {
      text: mytitle
    },
    legend: {
      enabled: false
    },
    xAxis: {
      categories: infocreated
    },
    series: [
      {
        data: myinfo
      }
    ]
  });
});

$('.hidechart').click(function() {
  $("#chartbox").hide();
  $("#incentivebox").hide();
  return $(".chart-backdrop").hide();
});

/*
  after a goal is completed, or changed in any way, then update it and email the teacher
*/


showCongrats = function() {
  $("#incentivebox").css('top', -90);
  $("#incentivebox").css('right', 430);
  placeincentivetext = '<p>' + congratulations + '</p>';
  $("#incentivetext").html(placeincentivetext);
  $("#incentivepic").css('background-image', incentivepic);
  $("#incentivebox").fadeIn("slow");
  return setTimeout("$('#incentivebox').hide();", 5000);
};

emailCompletion = function() {
  var postThis;
  postThis = {};
  postThis.notify = localStorage.getItem("notify");
  postThis.goalmessage = localStorage.getItem("goalmessage");
  console.log(goalmessage);
  return $.ajax({
    url: "goalNotify.php",
    type: "POST",
    data: postThis,
    success: function(response, textStatus, jqXHR) {
      return console.log("Yay, the email notify worked!");
    },
    error: function(jqXHR, textStatus, errorThrown) {
      return console.log("Didn't work so good...");
    }
  });
};

goalChange = function() {
  var postThis;
  postThis = {};
  postThis.goals = localStorage.getItem("goals");
  username = localStorage.getItem('username');
  postThis.userid = username;
  return $.ajax({
    url: "goalChange.php",
    type: "POST",
    data: postThis,
    success: function(response, textStatus, jqXHR) {
      return console.log("Yay, the goalChange save worked!");
    },
    error: function(jqXHR, textStatus, errorThrown) {
      return console.log("GoalChange save didn't work so good...");
    }
  });
};

primarygoalChange = function() {
  var postThis;
  postThis = {};
  postThis.primarygoals = localStorage.getItem("primarygoals");
  username = localStorage.getItem('username');
  postThis.userid = username;
  return $.ajax({
    url: "primarygoalChange.php",
    type: "POST",
    data: postThis,
    success: function(response, textStatus, jqXHR) {
      return console.log("Yay, the primaryGoal save worked!");
    },
    error: function(jqXHR, textStatus, errorThrown) {
      return console.log("PrimaryGoal save didn't work so good...");
    }
  });
};
