// Generated by CoffeeScript 1.6.3
/*global console*/

var activityChosen, createGoalList, datecreated, deadline, displayGoalList, displayUserList, goalsArray, init, showGoalsArray, showThatGoalList, showThatList, showThatUserList, showUserList, updatedList, userName, usersArray;

activityChosen = '';

showGoalsArray = [];

showUserList = '';

userName = '';

showThatList = '';

showThatUserList = '';

showThatGoalList = '';

deadline = '';

datecreated = '';

updatedList = '';

usersArray = [
  {
    datecreated: "",
    email: "",
    firstname: "JT",
    lastname: "Magee",
    username: "jtmagee",
    password: ""
  }
];

goalsArray = [
  {
    category: "personal",
    datecreated: "",
    deadline: "2013-10-20",
    goal: "go to store",
    goalid: 1,
    status: "completed",
    username: "jtmagee"
  }, {
    category: "personal",
    datecreated: "",
    deadline: "2013-10-21",
    goal: "buy beer",
    goalid: 2,
    status: "inprogress",
    username: "jtmagee"
  }, {
    category: "work",
    datecreated: "",
    deadline: "2013-10-22",
    goal: "throw computer",
    goalid: 3,
    status: "inprogress",
    username: "jtmagee"
  }, {
    category: "school",
    datecreated: "",
    deadline: "2013-10-23",
    goal: "ignore teacher",
    goalid: 4,
    status: "missed",
    username: "jtmagee"
  }
];

init = function() {
  displayUserList();
  if (localStorage.getItem("goalsArrayStored") === null) {
    localStorage.setItem("goalsArrayStored", JSON.stringify(goalsArray));
  }
  return createGoalList();
};

$('#addgoal').click(function() {
  return $("#addgoalform").show();
});

$('#savegoal').click(function() {
  var goalList;
  datecreated = new Date().toString();
  goalsArray = JSON.parse(localStorage["goalsArrayStored"]);
  goalsArray.push({
    status: "inprogress",
    category: $('#thecategory').val(),
    goal: $('#thegoal').val(),
    deadline: $('#thedeadline').val(),
    datecreated: datecreated,
    username: userName
  });
  localStorage.setItem("goalsArrayStored", JSON.stringify(goalsArray));
  goalList = $.grep(goalsArray, function(e) {
    return e.username === userName;
  });
  localStorage.setItem(userName + "Goals", JSON.stringify(goalList));
  console.log(goalList);
  $("#addgoalform").hide();
  $('#thegoal').val('');
  $('#thedeadline').val('');
  return displayGoalList();
});

$('#adduser').click(function() {
  return $("#adduserform").show();
});

$('#saveuser').click(function() {
  datecreated = new Date().toString();
  usersArray.push({
    firstname: $('#thefirstname').val(),
    lastname: $('#thelastname').val(),
    email: $('#theemail').val(),
    password: $('#thepassword').val(),
    datecreated: datecreated,
    username: $('#theusername').val()
  });
  localStorage.setItem("userlist", JSON.stringify(usersArray));
  $("#adduserform").hide();
  $('#thefirstname').val('');
  $('#thelastname').val('');
  $('#theemail').val('');
  $('#thepassword').val('');
  $('#thepasswordconfirm').val('');
  $('#theusername').val('');
  return displayUserList();
});

$(".users li").click(function() {
  var goalList;
  $(this).addClass('active').siblings("li").removeClass('active');
  userName = $(this).data("username");
  goalList = $.grep(goalsArray, function(e) {
    return e.username === userName;
  });
  localStorage.setItem(userName + "Goals", JSON.stringify(goalList));
  return displayGoalList();
});

$(".users").delegate("li", "click", function() {
  var goalList;
  $(this).addClass('active').siblings("li").removeClass('active');
  userName = $(this).data("username");
  goalList = $.grep(showGoalsArray, function(e) {
    return e.username === userName;
  });
  localStorage.setItem(userName + "Goals", JSON.stringify(goalList));
  return displayGoalList();
});

displayUserList = function() {
  showUserList = JSON.parse(localStorage["userlist"]);
  showThatUserList = showUserList.map(function(userlist) {
    return '<li data-username="' + userlist.username + '">' + '<span>' + userlist.firstname + ' ' + userlist.lastname + '</span>' + '<span><button type="button" class="btn btn-mini btn-danger pull-right"><b>X</b> </button></span><span class="clearfix"></span></li>';
  });
  return $(".users").css({
    "-ms-filter": "progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",
    "-moz-opacity": 1,
    "-khtml-opacity": 1,
    opacity: 1,
    visibility: "hidden"
  }).fadeOut(0, function() {
    $(".users").html(showThatUserList);
    return $(".users").css({
      visibility: "visible"
    }).fadeIn(200);
  });
};

createGoalList = function() {
  return showGoalsArray = JSON.parse(localStorage["goalsArrayStored"]);
};

displayGoalList = function() {
  var showList;
  showList = JSON.parse(localStorage[userName + "Goals"]);
  showThatGoalList = showList.map(function(goallist) {
    if (goallist.status === 'completed') {
      return '<li class="' + goallist.status + '">' + '<span class="goalcategory ' + goallist.category + '"></span>' + '<span class="goaltitle">' + goallist.goal + '</span>' + '<span class="goaldeadline">' + goallist.deadline + '</span>' + '<span class="goalstatus"><input type="checkbox" checked></span>' + '<span class="goalremove"><button type="button" class="btn btn-mini btn-danger"><b>X</b> </button></span><span class="clearfix"></span></li>';
    } else {
      return '<li class="' + goallist.status + '">' + '<span class="goalcategory ' + goallist.category + '"></span>' + '<span class="goaltitle">' + goallist.goal + '</span>' + '<span class="goaldeadline">' + goallist.deadline + '</span>' + '<span class="goalstatus"><input type="checkbox" ></span>' + '<span class="goalremove"><button type="button" class="btn btn-mini btn-danger"><b>X</b> </button></span><span class="clearfix"></span></li>';
    }
  });
  return $(".goals").css({
    "-ms-filter": "progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",
    "-moz-opacity": 1,
    "-khtml-opacity": 1,
    opacity: 1,
    visibility: "hidden"
  }).fadeOut(0, function() {
    $(".goals").html(showThatGoalList);
    return $(".goals").css({
      visibility: "visible"
    }).fadeIn(200);
  });
};

$('#all').click(function() {
  return $('.goals>li').show();
});

$('#completed').click(function() {
  return $('.goals>li.completed').show().siblings("li").hide();
});

$('#inprogress').click(function() {
  $('.goals>li.inprogress').show();
  $('.goals>li.completed').hide();
  return $('.goals>li.missed').hide();
});

$('#missed').click(function() {
  return $('.goals>li.missed').show().siblings("li").hide();
});
